// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/host";
import GlobalContextsProvider from "../../../components/plasmic/test/PlasmicGlobalContextsProvider";

import {
  PlasmicLoginServer,
  makeAppRouterPageCtx,
  generateDynamicMetadata,
  LoginServerSkeletonProps
} from "../../../components/plasmic/test/PlasmicLoginServer";
import type { Metadata, ResolvingMetadata } from "next";

export async function generateMetadata(
  { params, searchParams }: LoginServerSkeletonProps,
  parent: ResolvingMetadata
): Promise<Metadata> {
  const ctx = await makeAppRouterPageCtx({ params, searchParams });
  const metadata = generateDynamicMetadata({}, ctx);

  return { ...(await parent), ...metadata } as unknown as Metadata;
}

async function Login({ params, searchParams }: LoginServerSkeletonProps) {
  // Use PlasmicLogin to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicLogin are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicLogin is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).

  const ctx = await makeAppRouterPageCtx({ params, searchParams });
  return (
    <GlobalContextsProvider>
      <PageParamsProvider__
        route={ctx.pageRoute}
        params={ctx.params}
        query={ctx.query}
      >
        <PlasmicLoginServer />
      </PageParamsProvider__>
    </GlobalContextsProvider>
  );
}

export default Login;
