/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3RVpz8tf8oHM2jiuGYHU8J
// Component: wa2O1Rx8yCvZ

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { PromoBadge } from "@modules/common/components/promo-badge"; // plasmic-import: jxW6DR3Xs4OL/codeComponent
import Button from "../../Button"; // plasmic-import: vT52ykebc1Op/component
import { _useGlobalVariants } from "../blank_project/plasmic"; // plasmic-import: 3RVpz8tf8oHM2jiuGYHU8J/projectModule
import { _useStyleTokens } from "../blank_project/PlasmicStyleTokensProvider"; // plasmic-import: 3RVpz8tf8oHM2jiuGYHU8J/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicHomepage.module.css"; // plasmic-import: wa2O1Rx8yCvZ/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: I47xIOhj0rLT/icon
import ChevronDown2Icon from "./icons/PlasmicIcon__ChevronDown2"; // plasmic-import: mpLW5wjtyx0d/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_3RVpz8tf8oHM2jiuGYHU8J",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.root
          )}
        >
          <PromoBadge
            className={classNames("__wab_instance", sty.promoBadge__rxOw)}
            color={"#db2777"}
            text={"NEW"}
          />

          <div className={classNames("all", sty.freeBox___4WVcT)}>
            <PlasmicImg__
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={""}
              className={classNames(sty.img)}
              displayHeight={"40px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"none"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"40px"}
              src={{
                src: "/plasmic/test/images/image13.svg",
                fullWidth: 150,
                fullHeight: 150,
                aspectRatio: 1
              }}
            />

            <div className={classNames("all", sty.freeBox__qcmyH)}>
              <PlasmicLink__
                className={classNames(
                  "all",
                  "a",
                  "a__3RVpz",
                  "__wab_text",
                  sty.link__ukZgA
                )}
                component={Link}
                href={"https://www.plasmic.app/"}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"Services"}
              </PlasmicLink__>
              <PlasmicLink__
                className={classNames(
                  "all",
                  "a",
                  "a__3RVpz",
                  "__wab_text",
                  sty.link___2L7FI
                )}
                component={Link}
                href={"https://www.plasmic.app/"}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"Features"}
              </PlasmicLink__>
              <PlasmicLink__
                className={classNames(
                  "all",
                  "a",
                  "a__3RVpz",
                  "__wab_text",
                  sty.link__ugIyS
                )}
                component={Link}
                href={"https://www.plasmic.app/"}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"Contact"}
              </PlasmicLink__>
              <PlasmicLink__
                className={classNames(
                  "all",
                  "a",
                  "a__3RVpz",
                  "__wab_text",
                  sty.link__fmH8U
                )}
                component={Link}
                href={"https://www.plasmic.app/"}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"Log in"}
              </PlasmicLink__>
              <Button
                className={classNames("__wab_instance", sty.button__l17UQ)}
                color={"black"}
                end={
                  <ChevronDown2Icon
                    className={classNames("all", sty.svg__atvbH)}
                    role={"img"}
                  />
                }
                label={
                  <div
                    className={classNames("all", "__wab_text", sty.text__bq9F0)}
                  >
                    {"Sign up"}
                  </div>
                }
                start={
                  <CircleIcon
                    className={classNames("all", sty.svg__sYfky)}
                    role={"img"}
                  />
                }
              />
            </div>
          </div>
          <Button className={classNames("__wab_instance", sty.button__mGsRt)} />

          <div className={classNames("all", sty.freeBox__sSBo)} />

          <div className={classNames("all", "__wab_text", sty.text___7MWra)}>
            {"Home Page Created for the demo Purpose"}
          </div>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__3RVpz",
              "__wab_text",
              sty.link__pyLfg
            )}
            component={Link}
            href={"https://www.plasmic.app/"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Company"}
          </PlasmicLink__>
          <Button
            className={classNames("__wab_instance", sty.button___3Sm0Y)}
          />

          <Button className={classNames("__wab_instance", sty.button__dtVb6)} />

          <PromoBadge
            className={classNames("__wab_instance", sty.promoBadge__osJp8)}
            color={"#db2777"}
            text={"NEW"}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img"],
  img: ["img"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof PlasmicImg__;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/home",
      pagePath: "/home",
      params: {},
      query: {}
    })
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
