/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3RVpz8tf8oHM2jiuGYHU8J
// Component: yuEVZhguQr97

import * as React from "react";
import { DefaultTestPageProps } from "./PlasmicTestPage"; // plasmic-import: yuEVZhguQr97/render

import { ClientTestPage } from "../../../src/app/test-page/page-client"; // plasmic-import: yuEVZhguQr97/rscClient

const $$ = {};

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

function mkPathFromRouteAndParams(
  route: string,
  params: Record<string, string | string[] | undefined>
) {
  if (!params) {
    return route;
  }
  let path = route;
  for (const [key, value] of Object.entries(params)) {
    if (typeof value === "string") {
      path = path.replace(`[${key}]`, value);
    } else if (Array.isArray(value)) {
      if (path.includes(`[[...${key}]]`)) {
        path = path.replace(`[[...${key}]]`, value.join("/"));
      } else if (path.includes(`[...${key}]`)) {
        path = path.replace(`[...${key}]`, value.join("/"));
      }
    }
  }
  return path;
}

export interface TestPageServerSkeletonProps {
  params?: Promise<Record<string, string | string[] | undefined>>;
  searchParams?: Promise<Record<string, string | string[] | undefined>>;
}

export async function makeAppRouterPageCtx({
  params,
  searchParams
}: TestPageServerSkeletonProps) {
  const pageRoute = "/test-page";
  const pageParams = (await params) ?? {};
  const pagePath = mkPathFromRouteAndParams(pageRoute, pageParams);

  const ctx = {
    pageRoute,
    pagePath,
    params: pageParams,
    query: {}
  };
  return ctx;
}

export type PlasmicTestPageServerProps = DefaultTestPageProps &
  TestPageServerSkeletonProps;

export function PlasmicTestPageServer(props: PlasmicTestPageServerProps) {
  return <ClientTestPage {...props} />;
}
