/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3RVpz8tf8oHM2jiuGYHU8J
// Component: C8KO1p_P0FD2

"use client";

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/navigation";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/host";

import { generateDynamicMetadata, PageCtx } from "./PlasmicHelloTestServer"; // plasmic-import: C8KO1p_P0FD2/rscServer

import { LoginForm } from "@modules/account/components/auth-card/login-form"; // plasmic-import: NX-9i5iEb0B-/codeComponent
import { PromoBadge } from "@modules/common/components/promo-badge"; // plasmic-import: jxW6DR3Xs4OL/codeComponent
import { _useGlobalVariants } from "../blank_project/plasmic"; // plasmic-import: 3RVpz8tf8oHM2jiuGYHU8J/projectModule
import { _useStyleTokens } from "../blank_project/PlasmicStyleTokensProvider"; // plasmic-import: 3RVpz8tf8oHM2jiuGYHU8J/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicHelloTest.module.css"; // plasmic-import: C8KO1p_P0FD2/css

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

createPlasmicElementProxy;

export type PlasmicHelloTest__VariantMembers = {};
export type PlasmicHelloTest__VariantsArgs = {};
type VariantPropType = keyof PlasmicHelloTest__VariantsArgs;
export const PlasmicHelloTest__VariantProps = new Array<VariantPropType>();

export type PlasmicHelloTest__ArgsType = {};
type ArgPropType = keyof PlasmicHelloTest__ArgsType;
export const PlasmicHelloTest__ArgProps = new Array<ArgPropType>();

export type PlasmicHelloTest__OverridesType = {
  root?: Flex__<"div">;
  loginForm?: Flex__<typeof LoginForm>;
  promoBadge?: Flex__<typeof PromoBadge>;
};

export interface DefaultHelloTestProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHelloTest__RenderFunc(props: {
  variants: PlasmicHelloTest__VariantsArgs;
  args: PlasmicHelloTest__ArgsType;
  overrides: PlasmicHelloTest__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_3RVpz8tf8oHM2jiuGYHU8J",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.root
          )}
        >
          <LoginForm
            data-plasmic-name={"loginForm"}
            data-plasmic-override={overrides.loginForm}
            className={classNames("__wab_instance", sty.loginForm)}
            emailPlaceholder={"E-mail"}
            forgotLabel={"Forgot your password??"}
            passwordPlaceholder={"Password"}
            registerLabel={"Create Account"}
            registerPrompt={"Don't have an account?"}
            submitLabel={"Login"}
            title={"Welcome Back"}
          />

          <PromoBadge
            data-plasmic-name={"promoBadge"}
            data-plasmic-override={overrides.promoBadge}
            className={classNames("__wab_instance", sty.promoBadge)}
            color={"#db2777"}
            text={"hello test page"}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "loginForm", "promoBadge"],
  loginForm: ["loginForm"],
  promoBadge: ["promoBadge"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  loginForm: typeof LoginForm;
  promoBadge: typeof PromoBadge;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHelloTest__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHelloTest__VariantsArgs;
    args?: PlasmicHelloTest__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHelloTest__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHelloTest__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHelloTest__ArgProps,
          internalVariantPropNames: PlasmicHelloTest__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHelloTest__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHelloTest";
  } else {
    func.displayName = `PlasmicHelloTest.${nodeName}`;
  }
  return func;
}

export const PlasmicHelloTest = Object.assign(
  // Top-level PlasmicHelloTest renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    loginForm: makeNodeComponent("loginForm"),
    promoBadge: makeNodeComponent("promoBadge"),

    // Metadata about props expected for PlasmicHelloTest
    internalVariantProps: PlasmicHelloTest__VariantProps,
    internalArgProps: PlasmicHelloTest__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/hello-test",
      pagePath: "/hello-test",
      params: {},
      query: {}
    })
  }
);

export default PlasmicHelloTest;
/* prettier-ignore-end */
