/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3RVpz8tf8oHM2jiuGYHU8J
// Component: CYty2imRoz5Z

import * as React from "react";
import { DefaultLoginProps } from "./PlasmicLogin"; // plasmic-import: CYty2imRoz5Z/render

import { ClientLogin } from "../../../src/app/login/page-client"; // plasmic-import: CYty2imRoz5Z/rscClient

const $$ = {};

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "login",

    openGraph: {
      title: "login"
    },
    twitter: {
      card: "summary" as const,
      title: "login"
    }
  };
}

function mkPathFromRouteAndParams(
  route: string,
  params: Record<string, string | string[] | undefined>
) {
  if (!params) {
    return route;
  }
  let path = route;
  for (const [key, value] of Object.entries(params)) {
    if (typeof value === "string") {
      path = path.replace(`[${key}]`, value);
    } else if (Array.isArray(value)) {
      if (path.includes(`[[...${key}]]`)) {
        path = path.replace(`[[...${key}]]`, value.join("/"));
      } else if (path.includes(`[...${key}]`)) {
        path = path.replace(`[...${key}]`, value.join("/"));
      }
    }
  }
  return path;
}

export interface LoginServerSkeletonProps {
  params?: Promise<Record<string, string | string[] | undefined>>;
  searchParams?: Promise<Record<string, string | string[] | undefined>>;
}

export async function makeAppRouterPageCtx({
  params,
  searchParams
}: LoginServerSkeletonProps) {
  const pageRoute = "/login";
  const pageParams = (await params) ?? {};
  const pagePath = mkPathFromRouteAndParams(pageRoute, pageParams);

  const ctx = {
    pageRoute,
    pagePath,
    params: pageParams,
    query: {}
  };
  return ctx;
}

export type PlasmicLoginServerProps = DefaultLoginProps &
  LoginServerSkeletonProps;

export function PlasmicLoginServer(props: PlasmicLoginServerProps) {
  return <ClientLogin {...props} />;
}
