/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3RVpz8tf8oHM2jiuGYHU8J

"use client";

import * as React from "react";

import { _useGlobalVariants } from "../blank_project/plasmic"; // plasmic-import: 3RVpz8tf8oHM2jiuGYHU8J/projectModule
import { EmbedCss } from "@plasmicpkgs/plasmic-embed-css";

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  embedCssProps?: Partial<
    Omit<React.ComponentProps<typeof EmbedCss>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, embedCssProps } = props;

  return (
    <EmbedCss
      {...embedCssProps}
      css={
        embedCssProps && "css" in embedCssProps ? embedCssProps.css! : undefined
      }
    >
      {children}
    </EmbedCss>
  );
}
