// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/host";

import {
  PlasmicHelloTestServer,
  makeAppRouterPageCtx,
  generateDynamicMetadata,
  HelloTestServerSkeletonProps
} from "../../../components/plasmic/test/PlasmicHelloTestServer";
import type { Metadata, ResolvingMetadata } from "next";

export async function generateMetadata(
  { params, searchParams }: HelloTestServerSkeletonProps,
  parent: ResolvingMetadata
): Promise<Metadata> {
  const ctx = await makeAppRouterPageCtx({ params, searchParams });
  const metadata = generateDynamicMetadata({}, ctx);

  return { ...(await parent), ...metadata } as unknown as Metadata;
}

async function HelloTest({
  params,
  searchParams
}: HelloTestServerSkeletonProps) {
  // Use PlasmicHelloTest to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicHelloTest are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.

  const ctx = await makeAppRouterPageCtx({ params, searchParams });
  return (
    <PageParamsProvider__
      route={ctx.pageRoute}
      params={ctx.params}
      query={ctx.query}
    >
      <PlasmicHelloTestServer />
    </PageParamsProvider__>
  );
}

export default HelloTest;
