/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3RVpz8tf8oHM2jiuGYHU8J

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsexd9LxiNtfDh } from "../test/PlasmicGlobalVariant__Screen"; // plasmic-import: Exd9LxiNtfDh/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsexd9LxiNtfDh
});
