import * as React from "react"

// A plain, hand-written React component (NOT generated by Plasmic). This is the
// kind of "new component" you author in code and then expose to Plasmic Studio
// for drag-and-drop via registerComponent() in src/app/plasmic-host/registrations.ts.
export interface PromoBadgeProps {
  text?: string
  color?: string
  className?: string
}

// Named export — Plasmic codegen imports registered components by name
// (`import { PromoBadge } from ...`). A default export is also provided so both
// import styles resolve.
export function PromoBadge({
  text = "NEW",
  color = "#db2777",
  className,
}: PromoBadgeProps) {
  return (
    <span
      className={className}
      style={{
        display: "inline-block",
        background: color,
        color: "#fff",
        padding: "4px 12px",
        borderRadius: 999,
        fontSize: 12,
        fontWeight: 700,
        letterSpacing: "0.06em",
        textTransform: "uppercase",
      }}
    >
      {text}
    </span>
  )
}

export default PromoBadge
